image: docker:stable

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

stages:
  - buildenv
  - build
  - deploy

docker buildenv:
  stage: buildenv
  only:
    refs:
      - master
    changes:
      - .docker/buildenv/Dockerfile
  script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - cd .docker/buildenv
    - docker build -t jkcclemens/paste:latest .
    - docker push jkcclemens/paste:latest
    - docker logout

build:
  stage: build
  before_script:
    - apk add --no-cache binutils
  script:
    - docker run -v "$(pwd)":/paste jkcclemens/paste /root/.cargo/bin/cargo build --all --release
  after_script:
    - strip target/release/*.so target/release/webserver
  cache:
    key: '2019-11-25'
    paths:
      - target
  artifacts:
    paths:
      - target/release/*.so
      - target/release/webserver

deploy:
  stage: deploy
  before_script:
    - apk add --no-cache perl-utils
  script:
    - cp .docker/paste/* ./
    - mkdir exec
    - cp target/release/webserver target/release/*.so exec/
    - cd exec
    - find . -name '*.so' -print0 | xargs -0 shasum -a 256 >> shasums
    - cd ..
    - cp .gitignore .dockerignore
    - chmod +x run.sh
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker pull jkcclemens/paste-prebuilt:latest
    - docker pull jkcclemens/paste-prebuilt:"$CI_COMMIT_REF_SLUG" || true
    - docker build --cache-from jkcclemens/paste-prebuilt:latest --cache-from jkcclemens/paste-prebuilt:"$CI_COMMIT_REF_SLUG" -t jkcclemens/paste-prebuilt:"$CI_COMMIT_REF_SLUG" .
    - if [ "$(echo "$CI_COMMIT_REF_SLUG" | cut -d- -f1)" != "dependabot" ]; then docker push jkcclemens/paste-prebuilt:"$CI_COMMIT_REF_SLUG"; fi
    - if [ "$CI_COMMIT_REF_SLUG" = "master" ]; then docker tag jkcclemens/paste-prebuilt:master jkcclemens/paste-prebuilt:latest && docker push jkcclemens/paste-prebuilt:latest; fi
