language: rust
cache:
  cargo: true
  directories:
    - $HOME/libsodium
addons:
  apt:
    packages:
      - cmake
      - libpq-dev
before_script:
  - .travis/cache_check.sh
  - . .travis/libsodium.sh
script:
  - cargo build --verbose --all
# Remove the local crate's build files, as they only add bloat to the cache.
# TODO: Remove unused dependency build files
before_cache:
  - rm -rfv target/debug/{webserver,libworker_delete_directory,libworker_email,libworker_expire_paste}.d
  - rm -rfv target/debug/incremental/{build_script_build,webserver,worker_delete_directory,worker_email,worker_expire_paste}-*
  - rm -rfv target/debug/.fingerprint/{webserver,worker_delete_directory,worker_email,worker_expire_paste}-*
  - rm -rfv target/debug/build/{webserver,worker_delete_directory,worker_email,worker_expire_paste}-*
  - rm -rfv target/debug/deps/{webserver,worker_delete_directory,worker_email,worker_expire_paste}-*
  - cargo clean -p webserver
  - cargo clean -p worker_delete_directory
  - cargo clean -p worker_email
  - cargo clean -p worker_expire_paste
  # apparently cargo creates this file now? no reason to reupload the whole cache for it
  - rm -fv target/.rustc_info.json
rust:
  - nightly-2019-11-25
matrix:
  fast_finish: true
notifications:
  email: false
