cargo-features = ["edition"]

[package]
name = "webserver"
version = "0.1.1"
authors = ["Kyle Clemens <git@kyleclemens.com>"]

build = "build.rs"

edition = "2018"

exclude = [
  # pls
  # "web/",
  # "migrations/",
  "web/**/*",
  "migrations/**/*",
]

[badges]
travis-ci = { repository = "jkcclemens/paste", branch = "master" }
maintenance = { status = "actively-developed" }

[build-dependencies]
# getting current commit
git2 = "0.7"

[dependencies]
# all web logic
rocket_codegen = "0.3"

# json serialization and deserialization
serde = "1"
serde_derive = "1"
serde_json = "1"

# creating paste histories
git2 = "0.7"

# handling binary uploads in json
base64 = "0.9"

# error handling in the crate
failure = "0.1"

# accepting base64 gzip data
libflate = "0.1"

# accepting base64 xz data
xz2 = "0.1"

# secure password hashing
sodiumoxide = "0.1"

# environment variable loading
dotenv = "0.13"

# lazy statics
lazy_static = "1"

# complicated ifs with pattern matching
if_chain = "0.1"

# splitting on graphemes
unicode-segmentation = "1"

# making requests
reqwest = "0.8"

# configuration files
toml = "0.4"

# rate limiting (has to be outdated because this is the version diesel uses)
ipnetwork = "0.12"

# anti-csrf tokens
hex = "0.3"

# custom cookies (has to be outdated because this is the version Rocket uses)
cookie = "0.9"

# connection pooling
r2d2 = "0.8"

# in-memory data store - outdated until r2d2_redis updates
redis = "0.8"

# redis connection pooling
r2d2_redis = "0.7"

# username validation
unicode_categories = "0.1"

# email templates
tera = "0.11"

# html sanitizing
ammonia = "1"

# html parsing
html5ever = "0.22"

# url parsing
url = "1"

# comparing strings without case
unicase = "2"

# totp for two-factor authentication
oath = "0.10"

# encoding for totp shared keys
base32 = "0.3"

# displaying otpauth urls
qrcode = "0.8"

# handling qrcode images
image = "0.19"

# web logic
[dependencies.rocket]
version = "0.3"
features = ["tls"]

# web logic with json and uuids
[dependencies.rocket_contrib]
version = "0.3"
default_features = false
features = ["json", "uuid", "tera_templates"]

# unique paste-related ids
[dependencies.uuid]
version = "0.6"
features = ["v4", "serde"]

# database orm
[dependencies.diesel]
version = "1"
features = ["postgres", "uuid", "r2d2", "chrono", "network-address"]

# timestamp handling
[dependencies.chrono]
version = "0.4"
features = ["serde"]

# scheduling jobs
[dependencies.sidekiq]
# git because version on crates.io has incompatible version of r2d2
git = "https://github.com/spk/rust-sidekiq"

# markdown rendering
[dependencies.comrak]
version = "0.2"
default-features = false
