version: '3'
services:
  # This will run the latest published, successfully built commit on master.
  # Options for running other branches (e.g. stable) are coming soon.
  backend:
    image: jkcclemens/paste-prebuilt
    restart: unless-stopped
    volumes:
      - "../config.toml:/paste/config.toml"
      - "../Rocket.toml:/paste/Rocket.toml:ro"
      - "../.env:/paste/.env:ro"
      - "../webserver/web:/paste/web:ro"
      - "./nginx/certs:/paste/certs:ro"
      - "../.git:/paste/.git:ro"
      - "libraries:/libraries"
      - "store:/store"
    depends_on:
      - postgres
      - redis
      - sidekiq
    environment:
      - ROCKET_ENV=prod
  redis:
    image: redis:alpine
    restart: unless-stopped
  postgres:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=paste
      - POSTGRES_PASSWORD=paste
  sidekiq:
    build: sidekiq
    restart: unless-stopped
    depends_on:
      - redis
    volumes:
      - "../:/paste:ro"
      - "libraries:/libraries:ro"
      - "store:/store"
  camo:
    build: camo
    restart: unless-stopped
    environment:
      - CAMO_KEY=${CAMO_KEY}
      - CAMO_HOSTNAME=paste
  nginx:
    build: nginx
    restart: unless-stopped
    depends_on:
      - backend
      - camo
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./nginx/sites:/etc/nginx/sites:ro"
      - "./nginx/certs:/etc/nginx/certs:ro"
      - "./nginx/extra_modules:/etc/nginx/extra_modules:ro"
      - "../webserver/web/static:/etc/nginx/web/static:ro"
volumes:
  libraries:
  store:
